### ISSUE TITLE
[Critical] Calling a userdata object (not Instance) results in an unexpected error with Util

### ISSUE THREAD

**Issue by TheLegendarySpark** [Hexcede/H6x#16]
**Describe the bug**
Calling a user data object with the metamethod `__call` fails to check whether it's a C function, results in an error using [debug.info](https://developer.roblox.com/en-us/api-reference/lua-docs/debug) with argument 1.

**To Reproduce**
1. Create a module script that returns a user data object
2. Require the module and attempt to call the returned user data
3. Expect to see a bug similar to this
![Bug image](https://i.imgur.com/ZOW7JzE.jpeg)

**Expected behavior**
Calling it must not encounter an issue with user data

**Version information:**
 - H6x version: v2.1.0
 - Beta features enabled: Parallel Lua

**Comment by Hexcede** [comment]
Thank you for the report, I'll make sure to fix this soon.

**Comment by Hexcede** [comment]
This should be solved now in `2.1.1`. If you encounter any more issues, definitely let me know and feel free to reopen this issue. :smile:

**Comment by Hexcede** [comment]
Hey, @TheLegendarySpark, I have a question about the module you are requiring, particularly considering its related to Void SB. I feel like something's going on with this and I am quite confused.

I noticed that the module was updated on the 23rd to remove the returns on it, and I also noticed that you submitted this issue on the 22nd. I also noticed that the Void SB bot is down (since the 22nd) and the Void SB place was privated on the 22nd.

I'm also kind of curious about what FortuneX is, I couldn't find anything about it online, and I'm pretty confused about why you would want to run a sandbox inside of a sandbox. I have no idea what's going on but, it's too much to be a coincidence. Would you mind shooting me a DM on Discord?

@Hexcede#4563
