### ISSUE TITLE
Global table vulnerability?

### ISSUE THREAD

**Issue by TheLegendarySpark** [Hexcede/H6x#8]
There's a vulnerability inside user code where it can mess with the global H6X.

**Reproducing the bug**
1. Server Runner executes user code
```lua
warn(getfenv(2))
```
2. Bug occurs with the global table

**Expected behavior**
Prints out the global H6x table
```lua
FX Script 327713710-734a0c06164e71:  ▼  {
                    ["globalH6x"] =  ▼  {
                       ["Constants"] =  ▶ {...},
                       ["Environment"] =  ▶ {...},
                       ["Logger"] =  ▶ {...},
                       ["Reflector"] =  ▶ {...},
                       ["Runner"] =  ▶ {...},
                       ["Sandbox"] =  ▼  {
                          ["Empty"] =  ▶ {...},
                          ["Plugin"] =  ▶ {...},
                          ["Roblox"] =  ▶ {...},
                          ["User"] =  ▶ {...},
                          ["Vanilla"] =  ▶ {...},
                          ["new"] = "function"
                       },
                       ["SandboxActivity"] =  ▶ {...},
                       ["Testing"] =  ▶ {...},
                       ["Util"] =  ▶ {...}
                    },
                    ["globalSandbox"] =  ▶ {...},
                    ["globalThing"] = "someNotVerySpecificString",
                    ["script"] = Sandbox,
                    ["testMulti"] = "function",
                    ["thread"] = "Thread(24B3FD890F8)"
                 }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/39038022/173167215-b4bab6ea-06a9-45a9-bc7a-05b58b44280d.png)

**Version information (please complete the following information):**
 - H6x version: [v0.0.220515](https://github.com/Hexcede/H6x/releases/tag/v0.0.220515)
 - Beta features enabled: Parallel Lua

**Additional context**
I wasn't sure if this bug was necessary or not in terms of allowing user code to access the global H6X table. I wanted to point this out because it could access H6X module and possibly tamper its functions.

**Comment by Hexcede** [comment]
These globals are created by tests, and can't actually be accessed by sandboxed code (despite the fact that they can be set). When you call print with the caller fenv, print receives the original environment which has all of these values set.

This does however highlight that (by default) the base environment is shared across all sandboxed code, and, that is both counter-intuitive and not actually technically intended, it's just a side effect of my implementation that I clearly didn't consider at the time. The reason is that the default base environment is the fenv of the sandbox module (it calls `getfenv()`) when in reality it may be more intuitive and make more sense to use `getfenv(2)`. Alternatively, maybe instead of allowing the base environment to be modified I can allow all modifications to exist on a separate table specific to that `Environment` object.

I do encourage you to also try this with the v2.0 build of #7 in the Releases section because the behaviour may actually be fundamentally different.
